### PR TITLE
Added ImageView Example

### PR DESCRIPTION
**Pull request by WardsParadox**
Created an example after getting help from #python in macadmins slack for using an ImageView in Nibbler.

### CODE REVIEW

**Comment by erikng** [comment]
Awesome work Zack. Thanks for doing this.

**Comment by haircut** [comment]
That's awesome @WardsParadox – very useful example too! I'm totally stealing the device-specific image grabber; never seen that before.

**Comment by WardsParadox** [comment]
Glad I was able to contribute back, this tool has been an amazingly easy piece to integrate with here. Hopefully this will be useful for others are well. Working on combining it + pytds to create a good setup assistant for dropping with installapplications.

**Comment by WardsParadox** [comment]
@pudquick Any chance of having this merged or is the nibbler repo not accepting PR's atm?

**Comment by pudquick** [comment]
pewf!

**Pull request merged**
